/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
      extend: {
        "colors": {
                "primary": "#ffb4a3",
                "on-surface": "#f6ddd8",
                "inverse-surface": "#f6ddd8",
                "primary-fixed": "#ffdad2",
                "inverse-primary": "#ae3115",
                "tertiary-fixed-dim": "#e7c446",
                "on-secondary": "#003824",
                "surface-bright": "#453632",
                "on-error-container": "#ffdad6",
                "on-secondary-container": "#86c2a2",
                "secondary": "#97d3b3",
                "outline": "#a88a83",
                "surface-container-low": "#261815",
                "on-primary": "#630f00",
                "surface-variant": "#41312e",
                "surface-container-lowest": "#170b09",
                "surface-container-highest": "#41312e",
                "surface-container-high": "#352723",
                "error-container": "#93000a",
                "tertiary": "#e7c446",
                "on-background": "#f6ddd8",
                "primary-container": "#ff6b4a",
                "outline-variant": "#59413c",
                "on-tertiary-container": "#4d3e00",
                "on-primary-fixed": "#3d0600",
                "on-tertiary": "#3b2f00",
                "on-primary-fixed-variant": "#8c1900",
                "surface-tint": "#ffb4a3",
                "on-error": "#690005",
                "background": "#1d100e",
                "on-surface-variant": "#e1bfb8",
                "on-secondary-fixed-variant": "#135138",
                "secondary-fixed": "#b3f0ce",
                "secondary-fixed-dim": "#97d3b3",
                "error": "#ffb4ab",
                "surface": "#1d100e",
                "surface-container": "#2a1c19",
                "tertiary-container": "#c9a82b",
                "surface-dim": "#1d100e",
                "on-tertiary-fixed": "#231b00",
                "secondary-container": "#135138",
                "inverse-on-surface": "#3c2d29",
                "primary-fixed-dim": "#ffb4a3",
                "tertiary-fixed": "#ffe07c",
                "on-secondary-fixed": "#002113",
                "on-tertiary-fixed-variant": "#564500",
                "on-primary-container": "#661000"
        },
        "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
        },
        "spacing": {
                "md": "24px",
                "sm": "12px",
                "gutter": "24px",
                "xl": "80px",
                "base": "8px",
                "margin-desktop": "64px",
                "margin-mobile": "20px",
                "lg": "48px",
                "xs": "4px"
        },
        "fontFamily": {
                "body-lg": ["DM Sans", "sans-serif"],
                "body-md": ["DM Sans", "sans-serif"],
                "body-sm": ["DM Sans", "sans-serif"],
                "display-xl": ["Playfair Display", "serif"],
                "headline-sm": ["Playfair Display", "serif"],
                "display-lg": ["Playfair Display", "serif"],
                "display-lg-mobile": ["Playfair Display", "serif"],
                "headline-md": ["Playfair Display", "serif"],
                "label-mono": ["JetBrains Mono", "monospace"]
        },
        "fontSize": {
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "display-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
                "display-lg": ["48px", {"lineHeight": "1.2", "fontWeight": "600"}],
                "display-lg-mobile": ["36px", {"lineHeight": "1.2", "fontWeight": "600"}],
                "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "label-mono": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500"}]
        }
      },
    },
    plugins: [],
  }
